<LoadGraphics>
    FloatLayout:
        Button:
            text:"Volume & Weight"
            font_size:30
            size_hint:(.3, .1)
            pos_hint:{'x':0, 'y':0.9}

        Button:
            text:"RFID"
            font_size:30
            size_hint:(.3, .1)
            pos_hint:{'x':.35, 'y':.9}

        Button:
            text:"Loading"
            font_size:30
            size_hint:(.3, .1)
            pos_hint:{'x':.7, 'y':.9}
